### ISSUE TITLE
mpl, эпизод 1 : переносимость кода

### ISSUE THREAD

**Issue by avasyukov** [NikolayMorgunov/MPL-lab#1]
(Этого не было в материалах. И это почти офтоп. Но тем не менее.)

Вот эта строчка:
https://github.com/NikolayMorgunov/MPL-lab/blob/ea198c69c65f93bfeb5f2c130137c5c8db1563ff/ep1.py#L4

внезапно не переносима между разными операционными системами.

Потому что разделитель элементов пути по ФС разный в разных ОС. Идейно верно склеить кусочки пути (имя папки и имя файла) с помощью `os.path.join`.

**Comment by NikolayMorgunov** [comment]
Принял, исправлю

**Comment by NikolayMorgunov** [comment]
> (Этого не было в материалах. И это почти офтоп. Но тем не менее.)
> 
> Вот эта строчка:
> 
> https://github.com/NikolayMorgunov/MPL-lab/blob/ea198c69c65f93bfeb5f2c130137c5c8db1563ff/ep1.py#L4
> 
> внезапно не переносима между разными операционными системами.
> 
> Потому что разделитель элементов пути по ФС разный в разных ОС. Идейно верно склеить кусочки пути (имя папки и имя файла) с помощью `os.path.join`.

Принял, исправлю
